---
ID: "46b78bde-2310-428e-9ed9-c52dbf8a2001"
Parent: "71be571b-eb21-4ec8-baa2-09268976fb54"
Template: "71be571b-eb21-4ec8-baa2-09268976fb54"
Path: /sitecore/templates/Sitecore Demo/Pages/Contact Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{0706EFD9-7C20-4117-86BF-0EB4C2FB9B08}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200326T071758Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
