---
ID: "97aea1d1-4151-4a97-b644-f3680c6ac9ba"
Parent: "004fd93d-eb70-46ca-9867-27d24de23045"
Template: "004fd93d-eb70-46ca-9867-27d24de23045"
Path: /sitecore/templates/Sitecore Demo/Banners/Banner/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200206T140719Z
    - ID: "528421f4-4be9-4077-b7f9-f98a0d4724cd"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
