---
ID: "f97e976e-b585-44df-a90d-464d5e419653"
Parent: "c17566b2-02aa-43dc-8218-434e7b8d9e19"
Template: "c17566b2-02aa-43dc-8218-434e7b8d9e19"
Path: /sitecore/templates/Sitecore Demo/Common/Product TS/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Other/32x32/at.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200125T181955Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "881d1fcc-7b03-4f31-99a4-8d37c291401e"
      Hint: Text
      Value: $name
